trigger:
  - main

pool:
  name: JVS-NR-eastus2-pprdce01-ado-agentpool-01

variables:
  - group: dniprd  # Reference to your variable group

parameters:
  - name: methodName
    type: string
    default: "create_cloud_node"
    values:
      - "get_staging_client"
      - "create_cloud_node"
      - "assign_location"
      - "update_reachability"
      - "create_topology_vlan"
      - "delete_cloud_node"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.12'
      addToPath: true

  - script: |
      echo "Creating virtual environment..."
      python -m venv venv
      echo "Activating virtual environment..."
      source venv/bin/activate
      echo "Upgrading pip..."
      python -m pip install --upgrade pip
      echo "Installing dependencies from requirements.txt..."
      pip install --no-cache-dir -r code/dni/requirements.txt
      echo "Virtual environment setup complete."
    displayName: 'Set Up Virtual Environment and Install Dependencies'

  - script: |
      echo "Activating virtual environment..."
      source venv/bin/activate
      echo "Installed Python Packages:"
      pip list
    displayName: 'Verify Installed Python Packages in Virtual Environment'

  - script: |
      echo "Activating virtual environment..."
      source venv/bin/activate

      export tenant_id="${{ variables.tenant_id }}"
      export app_id="${{ variables.app_id }}"
      export passwd="${{ variables.passwd }}"
      export account_id="${{ variables.account_id }}"
      export rm_url="${{ variables.rm_url }}"
      export sa_connect_str="${{ variables.sa_connect_str }}"

      echo "Environment variables exported successfully:"
      echo "Tenant ID: $tenant_id"
      echo "App ID: $app_id"
      echo "Account ID: $account_id"
      echo "RM URL: $rm_url"
      echo "SA Connect String: [hidden]"

      echo "Executing the selected method..."
      venv/bin/python dni_client_demo.py --method ${{ parameters.methodName }}
    displayName: 'Run Python Script with Selected Method'