apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: svn-pipeline
spec:
  params:
    - name: url
      type: string
    - name: username
      type: string
    - name: password
      type: string
  tasks:
    - name: checkout-svn
      taskRef:
        name: svn-checkout
      params:
        - name: url
          value: $(params.url)
        - name: username
          value: $(params.username)
        - name: password
          value: $(params.password)
