apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: svn-checkout
spec:
  params:
    - name: url
      description: The URL of the SVN repository to checkout
      type: string
    - name: revision
      description: The revision of the SVN repository to checkout
      type: string
  resources:
    - name: workspace
      type: workspace
    - name: svn-secret
      type: secret
  steps:
    - name: svn-checkout
      image: subversion
      env:
        - name: SVN_USERNAME
          valueFrom:
            secretKeyRef:
              name: svn-secret
              key: username
        - name: SVN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: svn-secret
              key: password
        - name: SVN_URL
          value: $(params.url)
        - name: SVN_REVISION
          value: $(params.revision)
      command:
        - sh
        - -c
        - |
          svn checkout --username "${SVN_USERNAME}" --password "${SVN_PASSWORD}" \
            --revision "${SVN_REVISION}" "${SVN_URL}" "${resources.workspace.path}/repo"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
