apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: svn-checkout
spec:
  params:
    - name: url
      type: string
    - name: username
      type: string
    - name: password
      type: string
  steps:
    - name: checkout
      image: alpine/svn
      command:
        - sh
        - -c
        - |
          svn checkout --username $(inputs.params.username) --password $(inputs.params.password) $(inputs.params.url) /workspace/checkout
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      emptyDir: {}
